Fix Open API doc for DateTime requirements
nelmio/NelmioApiDocBundle pull request #1788
Opened 2021-03-11 18:07 UTC by raziel057

When using the following requierement:

```
@Rest\QueryParam(name="updatedFrom", strict=true, nullable=true, requirements=@Constraints\DateTime("Y-m-d\TH:i:s"))
```

According to the OpenAPI 3.0 documentation https://swagger.io/specification/, 

We should have ``"format": "date-time"`` rather than ``"format": "DateTime"`` in the generated doc

2021-03-14 15:28 UTC, GuilhemN commented
If we go this way, maybe we should somehow merge the logic with https://github.com/nelmio/NelmioApiDocBundle/blob/master/ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, what do you think?

2021-03-15 23:13 UTC, phansys reviewed
Could you please add a test covering this fix?

2021-03-16 09:47 UTC, phansys requested changes

2021-03-16 09:47 UTC, phansys commented on RouteDescriber/FosRestDescriber.php
> +                }
```suggestion
                }
                
                if ('Y-m-d' === $requirements->format) {
                    return 'date';
                }
```

2021-03-16 09:53 UTC, raziel057 commented
@phansys I just added the unit tests and fixed the CS

2021-03-16 09:55 UTC, phansys commented on Tests/Functional/Controller/FOSRestController.php
> +     * @RequestParam(name="date", requirements=@DateTime("Y-m-d"))
Could you please add test cases for other valid PHP date formats, like `"c"`?

2021-03-16 10:06 UTC, raziel057 commented
@phansys  I just added support for 'c' format

2021-03-16 10:23 UTC, phansys commented
> @phansys I just added support for 'c' format

I don't know if we should support these formats (`"c"`, `\DateTimeInterface::ATOM`, etc).
Mainly, my suggestion is about covering the case where the user uses other formats which are valid in PHP, but exposing that not all of them are valid for the OAS schema.
BTW, I'd like also be consistent with the behavior around this between describers.

2021-03-16 10:37 UTC, raziel057 commented
Maybe I'm wrong but for me if the provided format doesn't match the OA spec we should not set the ``date`` or ``date-time`` format.

2021-03-16 12:06 UTC, raziel057 commented
> 
> 
> If we go this way, maybe we should somehow merge the logic with https://github.com/nelmio/NelmioApiDocBundle/blob/master/ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, what do you think?

For me this point is not directly related and can be worked on another PR.

2021-03-18 15:08 UTC, raziel057 commented
When do you think this PR could be merged?

2021-03-21 16:02 UTC, phansys commented
>Maybe I'm wrong but for me if the provided format doesn't match the OA spec we should not set the date or date-time format.

I agree with that, is what I tried to say here:
>I don't know if we should support these formats ("c", \DateTimeInterface::ATOM, etc).
Mainly, my suggestion is about covering the case where the user uses other formats which are valid in PHP, but exposing that not all of them are valid for the OAS schema.

It would be nice to have test cases for scenarios where invalid OAS date formats (but valid for PHP) are passed, reflecting how the serialization behaves.

2021-03-24 17:07 UTC, raziel057 commented
@phansys I just fixed the format that should match according to the RFC3339 and added a new Assert for date with format that is not matching the RFC3339. In that case rather than generating a ``format: DateTime`` we doesn't set any format. At first I had in mind to generate a pattern given the date format but it seems overkill.

2021-03-24 18:29 UTC, phansys requested changes

2021-03-24 18:29 UTC, phansys commented on RouteDescriber/FosRestDescriber.php
> +                if (\DateTime::RFC3339 === $requirements->format || 'c' === $requirements->format) {
```suggestion
                if (\DateTimeInterface::RFC3339 === $requirements->format || 'c' === $requirements->format) {
```

2021-03-24 18:29 UTC, phansys commented on RouteDescriber/FosRestDescriber.php
> +                }
```suggestion
                }
                
                if ('Y-m-d' === $requirements->format) {
                    return 'date';
                }

                return null;
```
BTW, I think we should keep the existing behavior if the provided format is not supported or throw an exception in that case.

2021-03-25 11:26 UTC, raziel057 commented on RouteDescriber/FosRestDescriber.php
> +                if (\DateTime::RFC3339 === $requirements->format || 'c' === $requirements->format) {
\DateTimeInterface::RFC3339 is not supported by PHP 7.1 as you can see here:
https://github.com/nelmio/NelmioApiDocBundle/runs/2186348084

That's why I done the following change here:
https://github.com/nelmio/NelmioApiDocBundle/pull/1788/commits/d6a2d1240a853262a8005f6e4d8533127e1101f7

2021-03-25 11:50 UTC, raziel057 commented on RouteDescriber/FosRestDescriber.php
> +                }
Whether we add a ``format: DateTime`` or not at all in the resulting OA doc, the Rest Client Generator (.net) will create a string parameter as the DateTime format is unknown. So for me it should not appear as not supported by https://swagger.io/specification/. I'm not for throwing an exception as if someone wants to provide an other PHP supported datetime format it should be possible but just ignored by Open API.

2021-03-26 21:53 UTC, GuilhemN commented on RouteDescriber/FosRestDescriber.php
> +                }
Throwing an exception would be too bad for DX imo, ignoring the constraint in case we don't know what to do looks like a fine compromise to me.

2021-03-26 21:54 UTC, merged

2021-03-26 21:54 UTC, GuilhemN commented
Thank you @raziel057 and @phansys for you review!