Add self-describing model describer
nelmio/NelmioApiDocBundle pull request #1870
Opened 2021-09-06 10:11 UTC by tgalopin

This PR implements self-describing models: models that are able to describe their structure through a static method call.

I already use this technique in one of my projects with league/fractal (https://fractal.thephpleague.com): in Fractal, there is a concept of Transformers, classes that are able to transform a given object into an array. These transformers can be nested and used in collections.

Such transformers carry the output structure of my API: they are dedicated classes that I wish I could use as "models". They do not however match the currently available models describers. Thus I'd like to propose self-describing models: the ability for model classes to implement an interface and describe their structure in a static method:

```php
class SelfDescribingModel implements SelfDescribingModelInterface
{
    public static function describe(Schema $schema)
    {
        $schema->title = 'SelfDescribingTitle';
        $schema->properties = [/* ... */];
        // ...
    }
}
```

2021-09-15 09:41 UTC, GuilhemN commented
I like the idea 👍🏻
It's simple and easy to use, and can be useful for people preferring pure PHP over annotations.

And I guess this method could just return the value from a call to your transformer and everything would be fine, right?

I think I would just pass the `@Model` described as well to this new static method to take into account serialization context, and notably groups.

2022-05-16 11:01 UTC, chrisguitarguy requested changes

2022-05-16 11:01 UTC, chrisguitarguy commented on Tests/ModelDescriber/SelfDescribingModelDescriberTest.php
> +    }
This need a tests for the `supports` method as well -- both tests that pass supports and don't.

2022-12-21 10:28 UTC, tgalopin commented
PR rebased and updated

2022-12-21 15:50 UTC, chrisguitarguy approved these changes

2023-01-04 19:33 UTC, GuilhemN approved these changes

2023-01-04 19:33 UTC, GuilhemN commented
All good for me, thank you @tgalopin!

2023-01-04 19:34 UTC, merged