Add jms/serializer enum support
nelmio/NelmioApiDocBundle pull request #2078
Opened 2023-02-11 17:59 UTC by javer

`jms/serializer` introduced enum support since [v3.20](https://github.com/schmittjoh/serializer/releases/tag/3.20.0) and added a new type: https://github.com/schmittjoh/serializer/blob/402a12629e3ad6d6897273769808a28c32745309/src/Metadata/Driver/EnumPropertiesDriver.php#L50

And since `jms/serializer-bundle` [v5.2.1](https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/5.2.1) and https://github.com/schmittjoh/JMSSerializerBundle/pull/919 with `jms_serializer.enum_support: true` all existing models with enums got broken, because now enum properties are referenced to the fixed string `#/components/schemas/enum` instead of the correct `#/components/schemas/EnumClassName`:
```json
{
    "openapi": "3.0.0",
    "info": {},
    "paths": {
        "/api/card/random": {
            "get": {
                "operationId": "get_app_randomcardaction__invoke",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Card"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Card": {
                "properties": {
                    "rank": {
                        "type": "integer"
                    },
                    "suit": {
                        "$ref": "#/components/schemas/enum"
                    }
                },
                "type": "object"
            },
            "enum": {}
        }
    }
}
```

Before it was:
```json
{
    "openapi": "3.0.0",
    "info": {},
    "paths": {
        "/api/card/random": {
            "get": {
                "operationId": "get_app_randomcardaction__invoke",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Card"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Card": {
                "properties": {
                    "rank": {
                        "type": "integer"
                    },
                    "suit": {
                        "$ref": "#/components/schemas/Suit"
                    }
                },
                "type": "object"
            },
            "Suit": {
                "type": "string",
                "enum": [
                    "hearts",
                    "diamonds",
                    "clubs",
                    "spades"
                ]
            }
        }
    }
}
```

This PR adds support for enum type going from `jms/serializer` and returns the correct behavior.

2023-02-27 16:40 UTC, theofidry commented
I unfortunately have no permissions on this package, only the Alice one.

2023-03-01 13:16 UTC, Yozhef commented
@GuilhemN саn you review please?

2023-04-24 12:58 UTC, javer commented
Is there any update on this?

2023-05-16 12:26 UTC, szepczynski commented
@GuilhemN maybe you can help with review and merge this PR?

2023-09-06 08:54 UTC, javer commented
Any updates on this? @GuilhemN could you please take a look at this small fix?

2023-09-15 12:39 UTC, DjordyKoert commented
@javer can you please write test(s) for this new feature? Also please rebase on master 😄

2023-09-16 15:02 UTC, javer commented
@DjordyKoert Done: rebased on master, added test and even fixed codestyle in master 😄
Second commit is intended for keeping git history of JMSController.

2023-09-16 15:24 UTC, DjordyKoert requested changes

2023-09-16 15:24 UTC, DjordyKoert commented on ModelDescriber/JMSModelDescriber.php
> +            // See https://github.com/schmittjoh/serializer/blob/master/src/Metadata/Driver/EnumPropertiesDriver.php#L51
Its better to make this a permalink

2023-09-16 15:34 UTC, DjordyKoert commented on Tests/Functional/TestKernel.php
> +        }
`jms_serializer.enum_support` defaults to `false` even in PHP 8.1 or higher according to https://github.com/schmittjoh/JMSSerializerBundle/blob/master/Resources/doc/configuration.rst#extension-reference.
> `enum_support: true # PHP 8.1 Enums support, false by default for backward compatibility`

Might be better to test both with `false` & `true` options by adding an additional flag for this? Gonna leave this one for @GuilhemN to decide if this is needed or not.

2023-09-16 16:00 UTC, javer commented on Tests/Functional/TestKernel.php
> +        }
With `enum_support: false` test passes even without my change in `JMSModelDescriber`, so it would be strange to write a test which is not failing without the fix.

2023-09-16 16:04 UTC, DjordyKoert approved these changes
LGTM

2023-12-07 15:59 UTC, shakaran commented
LGTM :+1:

2024-01-04 15:02 UTC, shakaran commented
@javer could you rebase the conflicts? Thanks

2024-01-04 16:29 UTC, javer commented
Done, rebased on the latest master, and all tests are green.

2024-01-05 15:36 UTC, merged

2024-01-05 15:36 UTC, DjordyKoert commented
Thank you @javer!