feat: added symfony/uuid property describer
nelmio/NelmioApiDocBundle pull request #2098
Opened 2023-04-28 12:53 UTC by stollr

This describer adds support for UUIDs from the following libraries: symfony/uid and ramsey/uuid

This makes types of these classes configured as 
```
"type":  "string",
"format": "uuid",
"pattern": "^[0-9a-f]{8}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{12}$"
```

This is based on the [spec](https://swagger.io/docs/specification/data-models/data-types/#string).

2024-01-09 09:19 UTC, DjordyKoert requested changes

2024-01-09 09:19 UTC, DjordyKoert commented on DependencyInjection/NelmioApiDocExtension.php
> +
I think it makes more sense to only create the service if they do exists, instead of removing it.

2024-01-09 09:19 UTC, DjordyKoert commented on PropertyDescriber/UuidPropertyDescriber.php
> +            && (is_a($types[0]->getClassName(), Uuid::class, true)
Use the `AbstractUid` class instead just like Symfony's normalizer does https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/Serializer/Normalizer/UidNormalizer.php

2024-01-09 09:19 UTC, DjordyKoert commented on PropertyDescriber/UuidPropertyDescriber.php
> +                || is_a($types[0]->getClassName(), UuidInterface::class, true));
It doesn't look like Symfony's serializer supports this out of the box.

I think users of this bundle should implement their own  `PropertyDescriber` which describes the behaviour for describing it, because there is no way for us to know what `UuidInterface::toString()` will output.

2024-01-09 09:19 UTC, DjordyKoert commented on PropertyDescriber/UuidPropertyDescriber.php
> +        $property->pattern = '^[0-9a-f]{8}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{12}$';
This pattern might not necessarily be valid. 
https://github.com/symfony/symfony/blob/7bbc9be7ea7d607fa901edb2068c2cea13d24978/src/Symfony/Component/Serializer/Normalizer/UidNormalizer.php#L53-L62

2024-01-09 09:19 UTC, DjordyKoert commented
I would also like to see some test for this

2024-01-09 15:32 UTC, stollr commented on DependencyInjection/NelmioApiDocExtension.php
> +
Yeah, that makes sense ;-)

2024-01-09 15:34 UTC, stollr commented on PropertyDescriber/UuidPropertyDescriber.php
> +            && (is_a($types[0]->getClassName(), Uuid::class, true)
Done.

2024-01-09 15:58 UTC, stollr commented on PropertyDescriber/UuidPropertyDescriber.php
> +                || is_a($types[0]->getClassName(), UuidInterface::class, true));
> It doesn't look like Symfony's serializer supports this out of the box.

If the serializer is configured by the framework bundle it is the case (see [here](https://github.com/symfony/symfony/blob/7bbc9be7ea7d607fa901edb2068c2cea13d24978/src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php#L113)).

> I think users of this bundle should implement their own PropertyDescriber which describes the behaviour for describing it, because there is no way for us to know what UuidInterface::toString() will output.

Usually it should output a UUID. If this is not the case the user can override it with the property attribute. And if there is the demand one could extend the bundle's configuration to make if configurable.

I see an advantage in providing this describer out of the box, as it makes live easier for devs.

2024-01-09 20:52 UTC, DjordyKoert commented on PropertyDescriber/UuidPropertyDescriber.php
> +                || is_a($types[0]->getClassName(), UuidInterface::class, true));
> If the serializer is configured by the framework bundle it is the case (see [here](https://github.com/symfony/symfony/blob/7bbc9be7ea7d607fa901edb2068c2cea13d24978/src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php#L113)).

I am specifically talking about `Ramsey\Uuid\UuidInterface`. Serialization of this class is not explicitly supported by Symfony. 

It does work through a different normalizer ([JsonSerializableNormalizer](https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/Serializer/Normalizer/JsonSerializableNormalizer.php)) because it implements `JsonSerializable` but there is no real easy way (at the moment) for us to figure out what it would output. 

I don't think this bundle is the right place for describing Ramsey uuid at the moment.

2024-01-10 10:02 UTC, stollr commented on PropertyDescriber/UuidPropertyDescriber.php
> +                || is_a($types[0]->getClassName(), UuidInterface::class, true));
Okay, I understand and I am fine with that. I have removed the support of ramsey/uuid.

2024-01-10 10:09 UTC, stollr commented on PropertyDescriber/UuidPropertyDescriber.php
> +        $property->pattern = '^[0-9a-f]{8}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{12}$';
Okay, I have removed the pattern

2024-01-10 10:10 UTC, stollr commented
I'll try to add some.

2024-04-01 14:27 UTC, DominicLuidold requested changes
@stollr Any help needed with implementing test cases for this? 😃

2024-04-01 14:27 UTC, DominicLuidold commented on DependencyInjection/NelmioApiDocExtension.php
> +        // Remove UUID describer if none of the supported libraries exists
The comment is outdated

2024-04-01 14:27 UTC, DominicLuidold commented on PropertyDescriber/UuidPropertyDescriber.php
> +    use NullablePropertyTrait;
The trait has been deprecated with #2184 and can be removed in conjunction with calling `setNullableProperty` in line 26. 🙂

2024-04-02 17:30 UTC, stollr commented on DependencyInjection/NelmioApiDocExtension.php
> +        // Remove UUID describer if none of the supported libraries exists
Thanks. Fixed now

2024-04-02 17:30 UTC, stollr commented on PropertyDescriber/UuidPropertyDescriber.php
> +    use NullablePropertyTrait;
Fixed

2024-04-02 17:32 UTC, stollr commented
@DominicLuidold I have rebased the PR to current master. But running the tests, I get

> 1) Nelmio\ApiDocBundle\Tests\Command\DumpCommandTest::testJson with data set "pretty print" (array(), 192)
> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "sensio_framework_extra.controller.listener" has a dependency on a non-existent service "annotation_reader".

Any idea how to fix this?

2024-04-02 19:27 UTC, DominicLuidold commented
@stollr Let me know if I can help in any other way 😄

2024-04-02 22:06 UTC, stollr commented
@DominicLuidold I have added a functional and some unit tests and hope it is correct the way I did it.
Please let me know, if anything is missing or wrong.

2024-04-03 15:16 UTC, DjordyKoert requested changes

2024-04-03 15:16 UTC, DjordyKoert commented on composer.json
> +        "symfony/uid": "^5.1|^6.0|^7.0",
```suggestion
        "symfony/uid": "^5.4|^6.0|^7.0",
```

2024-04-03 15:16 UTC, DjordyKoert commented on src/DependencyInjection/NelmioApiDocExtension.php
> +        if (class_exists(\Symfony\Component\Uid\Uuid::class)) {
This check could be removed to `UuidPropertyDescriber::supports()` and always register the describer in the `.xml`.

2024-04-03 15:16 UTC, DjordyKoert commented on tests/Functional/Controller/ApiController81.php
> +    #[OA\Get(operationId: 'entity-with-uuid')]
Should not be needed for tests to function
```suggestion
```

2024-04-03 15:16 UTC, DjordyKoert commented on tests/Functional/Controller/ApiController80.php
> +     * @OA\Get(operationId="entity-with-uuid")
Should not be needed for tests to function
```suggestion
```

2024-04-03 15:16 UTC, DjordyKoert commented on tests/Functional/FunctionalTest.php
> +        $this->assertSame('uuid', $model->properties[0]->format);
I prefer testing the entire model instead of individual keys to prevent any unknown/unwanted changes from appearing in the future (extra keys for example).

You can see an example of this here 😄 https://github.com/nelmio/NelmioApiDocBundle/blob/4ff744fcaa21bdd6722e6c1772154eedc5982871/tests/Functional/FunctionalTest.php#L856

2024-04-03 15:16 UTC, DjordyKoert commented on tests/PropertyDescriber/UuidPropertyDescriberTest.php
> + */
I don't think this provides any benefits

```suggestion
```

2024-04-07 14:17 UTC, DominicLuidold commented on src/DependencyInjection/NelmioApiDocExtension.php
> +        if (class_exists(\Symfony\Component\Uid\Uuid::class)) {
Wouldn't it also make sense to register the `PropertyDescriberInterface` for autoconfiguration (just like with the `ModelDescriberInterface` a few lines above)?

With the approach of using the `supports()` method, all describers are registered in the `.xml` anyway and this would reduce the configuration effort both for the bundle and for project-specific/userland describers.

2024-04-28 16:23 UTC, stollr commented on composer.json
> +        "symfony/uid": "^5.1|^6.0|^7.0",
Fixed

2024-04-28 18:10 UTC, stollr commented on src/DependencyInjection/NelmioApiDocExtension.php
> +        if (class_exists(\Symfony\Component\Uid\Uuid::class)) {
@DjordyKoert There's already a check in the `supports` method. I am intentionally registering the service only if symfony/uid is installed, to prevent performance impact on projects not having installed symfony/uid. But I have moved the service declaration to a separate xml config file, like it was done with fos_rest.

@DominicLuidold You are right. Registering PropertyDescriberInterface for autoconfiguration makes sense. But this is out of scope of this PR.

2024-04-28 18:11 UTC, stollr commented on tests/Functional/Controller/ApiController81.php
> +    #[OA\Get(operationId: 'entity-with-uuid')]
I have removed it, now.

2024-04-28 18:11 UTC, stollr commented on tests/Functional/Controller/ApiController80.php
> +     * @OA\Get(operationId="entity-with-uuid")
I have removed it, now.

2024-04-28 18:12 UTC, stollr commented on tests/Functional/FunctionalTest.php
> +        $this->assertSame('uuid', $model->properties[0]->format);
This makes sense. I have adjusted the assertions.

2024-04-28 18:12 UTC, stollr commented on tests/PropertyDescriber/UuidPropertyDescriberTest.php
> + */
I have removed it, now.

2024-04-28 19:30 UTC, DjordyKoert commented
> @DjordyKoert I have addressed all comments and rebased the PR on master. I hope it is ready for merge, now :-)

Thanks I will try and have a look next week :)

2024-06-12 23:47 UTC, DjordyKoert approved these changes

2024-06-12 23:47 UTC, merged

2024-06-12 23:48 UTC, DjordyKoert commented
It took a bit, but it's now merged 😅 

Thank you @stollr!

2024-06-13 05:18 UTC, stollr commented
You're welcome. Thanks for merging