Allow `custom processors` through tagged services
nelmio/NelmioApiDocBundle pull request #2149
Opened 2023-11-16 16:08 UTC by Luehrsen

This pull request aims to provide a solution to register custom [processors](https://zircote.github.io/swagger-php/reference/processors.html) for `swagger-php` through services with the tag `swagger.processor`.

fixes #2146

2023-11-20 20:13 UTC, Nyholm requested changes
Thank you. 

I like it. It works. But what if we want to add a processor in the middle of the list? 

Could we register `Generator` as a service and use constructor injection to add that service to `ApiDocGenerator`? If so, we would be able to re-use `Generator::addProcessor($$processor, ?string $before = null)`.

2023-11-20 20:13 UTC, Nyholm commented on DependencyInjection/Compiler/CustomProcessorPass.php
> +        }
I dont see that this code it used.

2023-11-25 16:14 UTC, Luehrsen commented
Thank you for your feedback!

The 6.3.* test keep failing on me, but I think that's a general issue at the moment.

I think as of now we have a generally working solution for custom processors in `swagger-php`. 

One thing I noticed though, is that a lot of what the API Docs Bundle does is abstracted away from the processors, particularly anything relating the `ModelRegistry` and `ModelRegister`. There is a lot of logic happening there, that is inaccessible for custom processors at this point. (At least not with my skills.)

That means, that while this is a nice addition for the Bundle in general, it would not solve https://github.com/nelmio/NelmioApiDocBundle/issues/1721 for example, because you need access to the '@Model' and refs to do that.

I'm currently thinking about if we could find a way to pipe the ModelRegistry into a processor if needed.

2023-11-25 16:48 UTC, Nyholm approved these changes
This is awesome. 

I think this is great. Thank you for working on this.

2023-11-25 16:48 UTC, Nyholm commented on DependencyInjection/Compiler/CustomProcessorPass.php
> +        foreach ($container->findTaggedServiceIds('swagger.processor') as $id => $tags) {
Maybe prefix the tag with nelmio_api

2023-11-25 17:18 UTC, Luehrsen commented on DependencyInjection/Compiler/CustomProcessorPass.php
> +        foreach ($container->findTaggedServiceIds('swagger.processor') as $id => $tags) {
done

2023-11-25 17:37 UTC, Luehrsen commented
I think it should be in the scope of this PR to extend the `ModelRegister` a bit to attach some more useful information to the transformed annotations, so that the processors have some "meat" to work on. 

Does that make sens?

2023-11-26 10:57 UTC, Luehrsen commented
> I think it should be in the scope of this PR to extend the `ModelRegister` a bit to attach some more useful information to the transformed annotations, so that the processors have some "meat" to work on.
> 
> Does that make sense?

To answer my own question: Nope! I got it without touching the ModelRegister.

The secret sauce is to use `Nelmio\ApiDocBundle\OpenApiPhp\Util::getSchema` to get all the properties you desire.

So this would be an example of the `__invoke` function in a custom processor registered for `swagger-php`. (Dropping keywords here for search.)

```php

    const X_QUERY_AGS_REF = 'query-args-explode';

    public function __invoke(Analysis $analysis)
    {
	$this->analysis = $analysis;

        /** @var OA\Parameter[] $schemas */
        $parameters = $analysis->getAnnotationsOfType(OA\Parameter::class);

        foreach ($parameters as $parameter) {
            if ($parameter->x !== GENERATOR::UNDEFINED && array_key_exists(self::X_QUERY_AGS_REF, $parameter->x)) {
		// Generate the name from the parameter schema.
		$name = str_replace(OA\Components::SCHEMA_REF, '', $parameter->schema->ref);
		$schema = Util::getSchema($this->analysis->openapi, $name);
            }
        }
    }
```

This would result into `$schema` being a proper `OpenApi\Annotations\Schema` class with all the relevant properties attached. (So essentially the object the `ref` is pointing at. 

It was registered like this in a controller:
```php
	#[OA\Parameter(
		in: 'query',
		name: 'query',
		explode: true,
		style: 'form',
		schema: new OA\Schema(
			type: 'object',
			ref: new Model(
				type: TeamFilter::class,
				groups: ['read']
			)
		),
		x: [
			'query-args-explode' => true
		]
	)]
```

So to reiterate: If you want to access `Nelmio\ApiDocBundle\Annotation\Model` data inside a custom processor do this:

1) Find the property where the model was used. 
2) You'll see, that the model was replaced with an almost empty `Schema` object that now has a `ref` that points to your model, that has been processed by the `ModelRegistry`. 
3) To get the 'name' of your model as registered in the system, just remove the `OA\Components::SCHEMA_REF` from your `ref`. 
4) The base OpenAPI object can be found at `$analysis->openapi`. 
5) Use these two parameters inside `Nelmio\ApiDocBundle\OpenApiPhp\Util::getSchema` to retrieve the glory of your model.

2023-11-27 12:57 UTC, DjordyKoert requested changes

2023-11-27 13:28 UTC, Luehrsen commented on ApiDocGenerator.php
> +    public function __construct($describers, $modelDescribers, Generator $generator, CacheItemPoolInterface $cacheItemPool = null, string $cacheItemId = null)
Then we have to update the [container registration](https://github.com/nelmio/NelmioApiDocBundle/blob/3405e7b3beb5fae865f7dd52a1fce5e8013c95bd/DependencyInjection/NelmioApiDocExtension.php#L87) as well. Just changing this line leads to an error. 

I'm not quite sure how one would do that. Would it just be:

```php
                ->setArguments([
                    new TaggedIteratorArgument(sprintf('nelmio_api_doc.describer.%s', $area)),
                    new TaggedIteratorArgument('nelmio_api_doc.model_describer'),
                    null,
                    null,
                    new Reference('nelmio_api_doc.open_api.generator'),
                ]);
```

2023-11-27 13:44 UTC, DjordyKoert commented on ApiDocGenerator.php
> +    public function __construct($describers, $modelDescribers, Generator $generator, CacheItemPoolInterface $cacheItemPool = null, string $cacheItemId = null)
Ye that seems fine.

2023-11-27 13:47 UTC, DjordyKoert requested changes

2023-11-27 13:47 UTC, DjordyKoert commented on ApiDocGenerator.php
>      }
I made a small mistake with my previous suggestion, instantiating a new class like this is only supported since PHP 8.1.0.

```suggestion
    public function __construct($describers, $modelDescribers, CacheItemPoolInterface $cacheItemPool = null, string $cacheItemId = null, Generator $generator = null)
    {
        $this->describers = $describers;
        $this->modelDescribers = $modelDescribers;
        $this->cacheItemPool = $cacheItemPool;
        $this->cacheItemId = $cacheItemId;
        $this->generator = $generator ?? new Generator();
    }
```

2023-11-27 15:06 UTC, DjordyKoert approved these changes

2023-11-27 16:28 UTC, Nyholm commented
I've tested this in a SF 6 application. It works as expected. 

Thank you!

2024-01-02 13:07 UTC, merged

2024-01-02 13:08 UTC, DjordyKoert commented
Thank you @Luehrsen 😄