feat: symfony 7 support
nelmio/NelmioApiDocBundle pull request #2164
Opened 2023-12-11 10:53 UTC by faizanakram99

- makes doctrine/annotations optional
- updates tests and ci to test with both symfony 7 and < symfony 7 version
- adds routes-attributes.yaml file for symfony 7 compatible controllers/routes
- updates some fixtures to use attributes when sf7 kernel is installed
- skips tests/packages related to packages like jms serializer, bazinga, etc not supported by symfony 7 for symfony 7 matrix

Fixes #2143 and #2147, supersedes #2151 and #2155

#SymfonyHackday

2023-12-11 10:55 UTC, faizanakram99 commented
Tests are failing with this error, i am not sure why

```
Multiple @OA\Response() with the same response="200":
  \Nelmio\ApiDocBundle\Tests\Functional\Controller\InvokableController->__invoke() in path/to/NelmioApiDocBundle/Tests/Functional/Controller/InvokableController.php
```

```
  \Nelmio\ApiDocBundle\Tests\Functional\Controller\SerializedNameController->serializedNameAction() in path/to/NelmioApiDocBundle/Tests/Functional/Controller/SerializedNameController.php" at DefaultLogger.php line 31
```

2023-12-11 11:22 UTC, faizanakram99 commented
Ok from the looks of it, i don't think it will be possible to support both sf 7 and previous versions, sf 7 conflicts with sensio framework extra and it is probably required for all previous sf versions.

Looks like we need a major version bump and drop all those packages altogether.

2023-12-11 14:14 UTC, DjordyKoert approved these changes
Thanks a lot :)

2023-12-11 14:14 UTC, DjordyKoert commented on Tests/Functional/Entity/SymfonyConstraintsWithValidationGroups.php
> +use OpenApi\Attributes\Property;
We could also keep the same use notation. Will leave this up to you :)
```php
use OpenApi\Attributes as OAT
```

2023-12-11 14:14 UTC, DjordyKoert commented on Tests/Functional/TestKernel.php
> -     */
Why was this one removed?

2023-12-11 14:14 UTC, DjordyKoert commented on Tests/Functional/TestKernel.php
> -     */
Same for this one

2023-12-11 14:37 UTC, DjordyKoert requested changes

2023-12-11 15:04 UTC, faizanakram99 commented on Tests/Functional/TestKernel.php
> -     */
It's probably cs fixer, I ran cs fix on whole Tests folder with `@Symfony` rules

2023-12-11 15:07 UTC, DjordyKoert commented on Tests/Functional/TestKernel.php
> -     */
Ah thats what I assumed as well, just making sure

2023-12-11 15:11 UTC, faizanakram99 commented on .github/workflows/continuous-integration.yml
> +        if: matrix.symfony-require == '7.0'
yes indeed

2023-12-11 15:46 UTC, RobertMe commented
I find it quite rude to use mine (and @DjordyKoert) our changes and commit them under your own name. Especially since at least my PR is waiting for review, and not because I abondended it (/not because didn't incorperate requested changes).

Your could have just merged both branches / pull requests into your own branch so it would be clear that someone else wrote the code, and add your own changes on top of it.

2023-12-11 15:52 UTC, faizanakram99 commented on Tests/Functional/Entity/SymfonyConstraintsWithValidationGroups.php
> +use OpenApi\Attributes\Property;
done

2023-12-11 15:52 UTC, faizanakram99 commented on .github/workflows/continuous-integration.yml
> +        if: matrix.symfony-require == '7.0'
fixed

2023-12-11 15:56 UTC, faizanakram99 commented
> I find it quite rude to use mine (and @DjordyKoert) our changes and commit them under your own name. Especially since at least my PR is waiting for review, and not because I abondended it (/not because didn't incorperate requested changes).
> 
> Your could have just merged both branches / pull requests into your own branch so it would be clear that someone else wrote the code, and add your own changes on top of it.

apologies, i did mention it in a comment that I missed that there was a PR https://github.com/nelmio/NelmioApiDocBundle/pull/2151#issuecomment-1849886108

Later I tried to fork your repositories so that I add my changes on top of it but since I had already made all the changes locally (including both making doctrine/annotations optional and adding sf 7 support), i found it hard to separate them and apply on top of your changes. If you wish, I can give you write permissions to this repository (actually you and @DjordyKoert both), so that you may re-add your commits or even ammend existing commits.

It doesn't really matter to me whom the commits are attributed to, I want support for sf7 in this lib because we are using it  and it is blocking our sf 7 upgrade and it seemed a good task for symfony hack day. Again apology for any miscommunications.

2023-12-11 16:00 UTC, DjordyKoert commented
> I find it quite rude to use mine (and @DjordyKoert) our changes and commit them under your own name. Especially since at least my PR is waiting for review, and not because I abondended it (/not because didn't incorperate requested changes).
> 
> Your could have just merged both branches / pull requests into your own branch so it would be clear that someone else wrote the code, and add your own changes on top of it.

I personally have no issue with my 'changes'/commits being lost, since my PR contained the bare minimum (and didn't even work to begin with). I am just very happy @faizanakram99 was able to make it (almost? because CI is still failing) work for Symfony 7. 😄

2023-12-11 16:04 UTC, DjordyKoert commented
> Tests are failing with this error, i am not sure why
> 
> ```
> Multiple @OA\Response() with the same response="200":
>   \Nelmio\ApiDocBundle\Tests\Functional\Controller\InvokableController->__invoke() in path/to/NelmioApiDocBundle/Tests/Functional/Controller/InvokableController.php
> ```
> 
> ```
>   \Nelmio\ApiDocBundle\Tests\Functional\Controller\SerializedNameController->serializedNameAction() in path/to/NelmioApiDocBundle/Tests/Functional/Controller/SerializedNameController.php" at DefaultLogger.php line 31
> ```

I can also reproduce this locally. This is a very weird one since it's appending the response from `InvokableController` to the `SerializedNameController` `/api/serializename` path?????

2023-12-12 00:31 UTC, DjordyKoert commented
@faizanakram99 I have created a PR on your fork repo with changes to make phpunit work for Symfony 7. https://github.com/faizanakram99/NelmioApiDocBundle/pull/1

Older versions are still failing but this should be a good starting point for fixing the others 😄

2023-12-12 07:46 UTC, faizanakram99 commented
> @faizanakram99 I have created a PR on your fork repo with changes to make phpunit work for Symfony 7. [faizanakram99#1](https://github.com/faizanakram99/NelmioApiDocBundle/pull/1)
> 
> Older versions are still failing but this should be a good starting point for fixing the others 😄

Thank you so much @DjordyKoert , I've merged your changes (with rebase)

I think you also need to run cs-fix on changed files, style ci is complaining

2023-12-13 16:29 UTC, derrabus commented on .github/workflows/continuous-integration.yml
> +          composer remove friendsofsymfony/rest-bundle sensio/framework-extra-bundle jms/serializer-bundle willdurand/hateoas-bundle --no-update --dev
`jms/serializer-bundle` and `willdurand/hateoas-bundle` have been fixed in the meantime.

2023-12-19 16:09 UTC, DjordyKoert commented
@faizanakram99 https://github.com/faizanakram99/NelmioApiDocBundle/pull/2

I finally managed to fix each and every failing test (minus 7.2 https://github.com/nelmio/NelmioApiDocBundle/pull/2162 fixes this) (this was quite the task 😬). Could you kindly merge this into this PR. 

After this is done we simply need to wait for one of the maintainers to merge this and then Nelmio will officially have Symfony 7 support! 🚀

2023-12-19 21:56 UTC, DjordyKoert commented
@faizanakram99 could you please run a style fix 😄

2023-12-19 22:17 UTC, DjordyKoert approved these changes

2023-12-20 13:23 UTC, DjordyKoert commented
> @faizanakram99 could you please run a style fix 😄, mine doesn't really fix anything for some reason

Nevermind that, I simply applied the diff from styleci https://github.com/faizanakram99/NelmioApiDocBundle/pull/3 😃 

@faizanakram99 a merge and styleci should be fixed

2023-12-20 13:31 UTC, DjordyKoert commented
@GuilhemN any possibility you can look at this? ❤️

2023-12-20 14:37 UTC, fabianoroberto commented on .github/workflows/continuous-integration.yml
> +          composer update --no-interaction --no-progress ${{ matrix.composer-flags }}
Why this line appear twice `composer update --no-interaction --no-progress ${{ matrix.composer-flags }}`

2023-12-31 14:21 UTC, Gemorroj commented
@GuilhemN ping

2023-12-31 16:52 UTC, merged

2023-12-31 16:53 UTC, GuilhemN commented
Thank you very much for the huge work!
I will try to look into fixing the CI a bit later.

Happy new year, best wishes!

2023-12-31 16:55 UTC, DjordyKoert commented
Thank you very much @GuilhemN !

Happy new years & best wishes to you too :heart: