fix(#2222): Fix default value properties getting marked as required
nelmio/NelmioApiDocBundle pull request #2248
Opened 2024-03-29 21:40 UTC by DominicLuidold

| Q             | A                                                                                                                         |
|---------------|---------------------------------------------------------------------------------------------------------------------------|
| Bug fix?      | yes                                                                                                                    |
| New feature?  | no                                                                    |
| Deprecations? | no                                                   |
| Issues        | Fix #2222  |

This PR fixes the following two bugs:
* Promoted properties with a value initialized by the constructor are not considered to have a default value and are therefore not returned by `ReflectionClass::getDefaultProperties()`.[^1]
* The `SymfonyConstraintAnnotationReader::processPropertyAnnotations()` method is called before a property's default value is set and additionally doesn't consider a possible set default value.

[^1]: https://bugs.php.net/bug.php?id=81386

2024-03-29 21:59 UTC, DominicLuidold commented
@DjordyKoert tests are failing with PHP 7.4 because of the promoted constructor properties syntax in the two newly added test entities. Do you have an approach in mind how to prevent those failures?

I've thought of wrapping the entity classes and methods within the `ApiController`s with `if (PHP_VERSION_ID < 80000) {` but I'm not sure if that's the correct approach here.. :thinking:

2024-03-29 22:57 UTC, DjordyKoert requested changes

2024-03-29 22:57 UTC, DjordyKoert commented on src/ModelDescriber/ObjectModelDescriber.php
> +            if (!$parameter->isDefaultValueAvailable() || null === $parameter->getDefaultValue()) {
`null` could be a valid default value, this check seems unnecessary.

```suggestion
            if (!$parameter->isDefaultValueAvailable()) {
```

2024-03-29 22:57 UTC, DjordyKoert commented on src/ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php
> +                if (true === $property->nullable || !Generator::isDefault($property->default)) {
It does not seem to make sense to check `true === $property->nullable` on an annotation of type `Assert\NotNull`

2024-03-29 22:57 UTC, DjordyKoert commented on tests/Functional/Entity/EntityWithPromotedPropertiesWithDefaults81.php
> +    ) {
Preferably add some more parameters options here for tests:
- `string $...,` - No default value specified for a non-promoted property
- `?string $...,` - No default value specified for a nullable non-promoted property
- `?string $... = null,` - `null` default value specified for a nullable non-promoted property
- `public ?string $... = null,` - `null` default value specified for a nullable promoted property

2024-03-29 22:57 UTC, DjordyKoert commented on tests/Functional/Controller/ApiController80.php
> +     * @Route("/entity-with-falsy-defaults", methods={"GET"})
This change seems accidental and unrelated

```suggestion
     * @Route("/entity-with-falsy-defaults", methods={"POST"})
```

2024-03-29 23:01 UTC, DjordyKoert commented
> @DjordyKoert tests are failing with PHP 7.4 because of the promoted constructor properties syntax in the two newly added test entities. Do you have an approach in mind how to prevent those failures?
> 
> I've thought of wrapping the entity classes and the methods within the `ApiController`s with `if (PHP_VERSION_ID >= 80000) {` but I'm not sure if that's the correct approach here.. 🤔

I think it's okay to simply wrap the entity class (`EntityWithPromotedPropertiesWithDefaults80`) with an if-else statement and create an empty class for PHP 7.4, the class should and cannot be tested on 7.4 anyway

2024-03-30 09:39 UTC, DominicLuidold commented on tests/Functional/Controller/ApiController80.php
> +     * @Route("/entity-with-falsy-defaults", methods={"GET"})
Good catch! :sweat_smile:

2024-03-30 10:17 UTC, DominicLuidold commented
@DjordyKoert Thanks for your fast response and the code review/input! I've addressed all the open points and was also able to get the tests running with PHP 7.4. :blush:

Unfortunately, the test now fails on PHP 8.0 only and I really can't get my head around why. [According to the job log](https://github.com/nelmio/NelmioApiDocBundle/actions/runs/8490044202/job/23260744858), the `EntityWithPromotedPropertiesWithDefaults80` is declared more than once:
```
PHP Fatal error:  Cannot declare class EntityWithPromotedPropertiesWithDefaults80, because the name is already in use in /home/runner/work/NelmioApiDocBundle/NelmioApiDocBundle/tests/Functional/Entity/EntityWithPromotedPropertiesWithDefaults80.php(17) : eval()'d code on line 4
```

But this isn't the case. I also manually checked the code beforehand and as far as I'm concerned, it should work. See https://3v4l.org/d0p5L#v8.0.30 with no error output. Am I missing something obvious here? :thinking: :sweat_smile:

2024-03-30 14:29 UTC, DjordyKoert commented
> @DjordyKoert Thanks for your fast response and the code review/input! I've addressed all the open points and was also able to get the tests running with PHP 7.4. 😊

Thank you!

> Unfortunately, the test now fails on PHP 8.0 only and I really can't get my head around why. [According to the job log](https://github.com/nelmio/NelmioApiDocBundle/actions/runs/8490044202/job/23260744858), the `EntityWithPromotedPropertiesWithDefaults80` is declared more than once:
> 
> ```
> PHP Fatal error:  Cannot declare class EntityWithPromotedPropertiesWithDefaults80, because the name is already in use in /home/runner/work/NelmioApiDocBundle/NelmioApiDocBundle/tests/Functional/Entity/EntityWithPromotedPropertiesWithDefaults80.php(17) : eval()'d code on line 4
> ```
> 
> But this isn't the case. I've also manually checked the code beforehand and as far as I'm concerned, it should work. See [3v4l.org/d0p5L#v8.0.30](https://3v4l.org/d0p5L#v8.0.30) with no error output. Am I missing something obvious here? 🤔 😅

I got no idea why your setup wouldn't work but I have moved this this to its own controller instead of building more onto the `ApiController..`

2024-03-30 14:34 UTC, DjordyKoert approved these changes
@DominicLuidold could you see if I missed anything by any chance? 😄

2024-03-30 14:41 UTC, DominicLuidold reviewed
Just two nit-picky things. Thanks a lot for your support @DjordyKoert! :pray:

2024-03-30 14:41 UTC, DominicLuidold commented on tests/Functional/Controller/PromotedPropertiesController80.php
> +
The license header is missing here

2024-03-30 14:41 UTC, DominicLuidold commented on tests/Functional/Controller/PromotedPropertiesController81.php
> +
Here as well :slightly_smiling_face:

2024-03-30 14:44 UTC, DjordyKoert commented on tests/Functional/Controller/PromotedPropertiesController80.php
> +
Thanks!

2024-03-30 14:46 UTC, merged

2024-03-30 14:46 UTC, DjordyKoert commented
Thank you very much @DominicLuidold!