phpstan installation
nelmio/NelmioApiDocBundle pull request #2249
Opened 2024-03-30 15:59 UTC by DjordyKoert

| Q             | A                                                                                                                         |
|---------------|---------------------------------------------------------------------------------------------------------------------------|
| Bug fix?      | no                                                                                                                    |
| New feature?  | no                                                                    |
| Deprecations? | no                                                   |
| Issues        |  |

Adds PHPStan

2024-04-01 15:29 UTC, DominicLuidold requested changes
@DjordyKoert I hope you don't mind some input even though your PR is still marked as a draft. Also, it looks more than it is 😅

Thanks for implementing PHPStan! 😄

2024-04-01 15:29 UTC, DominicLuidold commented on composer.json
> +        "phpstan/extension-installer": "^1.3"
The extension installer is a really handy tool, but I would consider not adding a dependency if it's not really necessary - mainly to minimize the impact of bugs or unintended side effects, even if it's "just" a dev dependency.

To achieve the same result, only five lines would've to be added to the config file:
```yaml
includes:
    - vendor/phpstan/phpstan-phpunit/extension.neon
    - vendor/phpstan/phpstan-phpunit/rules.neon
    - vendor/phpstan/phpstan-symfony/extension.neon
    - vendor/phpstan/phpstan-symfony/rules.neon
```

2024-04-01 15:29 UTC, DominicLuidold commented on composer.json
> +        "phpstan/phpstan": "^1.10",
[`phpstan/phpstan-strict-rules`](https://github.com/phpstan/phpstan-strict-rules) could be a useful extension as well

2024-04-01 15:29 UTC, DominicLuidold commented on phpstan.neon
> +parameters:
If I'm not mistaken, the `symfony.containerXmlPath` parameter needs to be configured to make full use of the extension (see https://github.com/phpstan/phpstan-symfony?tab=readme-ov-file#configuration)

2024-04-02 10:52 UTC, DjordyKoert commented on phpstan.neon
> +    level: 6
I am not against increasing it, but I need to slowly work through the different levels in this PR first hahaha 😅 

Locally I will slowly walk through each level (1 -> 2 -> 3 e.t.c.) because even the lower levels are triggering phpstan for quite some things.

After that I can make a better decision about which level would be good, I would prefer 9.

2024-04-02 10:53 UTC, DjordyKoert commented on composer.json
> +        "phpstan/phpstan": "^1.10",
👍

2024-04-02 10:58 UTC, DjordyKoert commented on phpstan.neon
> +parameters:
I have seen that this isn't needed because it was able to correctly give the types for `TreeBuilder` and `NodeDefinition` objects for example. This is most likely only needed for the container related features:
> - Notifies you when you try to get an unregistered service from the container.
> - Notifies you when you try to get a private service from the container.

2024-04-02 11:00 UTC, DjordyKoert commented on composer.json
> +        "phpstan/extension-installer": "^1.3"
it would not hurt to not use it 👍 

manual entries to the phpstan config could even help some people understand what it's doing for people not familiair with phpstan

2024-04-05 07:43 UTC, DominicLuidold commented on phpstan.neon
> +    level: 6
> I am not against increasing it, but I need to slowly work through the different levels in this PR first hahaha 😅

Makes sense :blush: 

> After that I can make a better decision about which level would be good, I would prefer 

That would be optimal, of course. Let's see how feasible it is to do all in one go or if maybe multiple smaller PRs make sense. 🙂

2024-04-05 07:43 UTC, DominicLuidold commented on phpstan.neon
> +parameters:
Even better :smile:

2024-04-05 17:14 UTC, DjordyKoert commented on phpstan.neon
> +    level: 6
@DominicLuidold I think it is reasonable to stop at level 5 inside this PR. level 6 is reporting **a lot** of errors because of missing typehints:
- `src/`: [ERROR] Found 264 errors
- `tests/`: [ERROR] Found 325 errors

It's probably best to move to level 6 inside a different PR to make sure no accidental breaking changes get added by adding typehints in places.

2024-04-06 11:26 UTC, DominicLuidold requested changes
Great effort - I really think this will help the bundle long term! :smile: 

I only found some very minor things :slightly_smiling_face:

2024-04-06 11:26 UTC, DominicLuidold commented on src/Describer/OpenApiPhpDescriber.php
> +            trigger_deprecation('nelmio/api-doc-bundle', '4.25.1', 'The "$overwrite" argument of "%s" is unused and therefore deprecated.', __METHOD__);
Wouldn't this have to be 
```suggestion
            trigger_deprecation('nelmio/api-doc-bundle', '4.25.2', 'The "$overwrite" argument of "%s" is unused and therefore deprecated.', __METHOD__);
```
as `4.25.1` has already been released?

2024-04-06 11:28 UTC, DominicLuidold commented on phpstan.neon
> adding phpstan.neon to the .gitignore file, so that you can use a different config locally, e.g. for testing purposes.

If possible, I'd add this as part of this PR as well :)

2024-04-06 11:32 UTC, DominicLuidold requested changes

2024-04-06 11:32 UTC, DominicLuidold commented on phpstan.dist.neon
> This change would also open up the possibility of adding phpstan.neon to the .gitignore file, so that you can use a different config locally, e.g. for testing purposes.

If possible, I'd add this as part of this PR as well :)

2024-04-06 11:45 UTC, DjordyKoert commented on phpstan.dist.neon
missed that one, thank you :)

2024-04-06 11:54 UTC, DjordyKoert commented
> Great effort - I really think this will help the bundle long term! 😄
> 
> I only found some very minor things 🙂

Thank you very much for reviewing this 😄

2024-04-06 11:57 UTC, DominicLuidold approved these changes

2024-04-06 12:08 UTC, merged