Add ability to configure UI through configuration
nelmio/NelmioApiDocBundle pull request #2251
Opened 2024-04-01 23:58 UTC by HypeMC

| Q             | A                                                                                                                         |
|---------------|---------------------------------------------------------------------------------------------------------------------------|
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | -

Adds the ability to configure the UI through configuration:

```yaml
nelmio_api_doc:
  html_config:
    expandResponses: '200,201'
    hideDownloadButton: true
```

2024-04-01 23:59 UTC, HypeMC commented on templates/SwaggerUi/index.html.twig
> +            };
This made no sense as the `loadSwaggerUI()` function doesn't return anything.

2024-04-01 23:59 UTC, HypeMC commented on templates/Redocly/index.html.twig
> +</body>
The closing body tag was missing.

2024-04-05 18:16 UTC, DjordyKoert commented on src/DependencyInjection/Configuration.php
> +                    ->ignoreExtraKeys(false)
Would it make sense to separate the configurations for SwaggerUI & Redocly? It is technically possible to use both UI's on different paths

2024-04-08 00:00 UTC, HypeMC commented on src/DependencyInjection/Configuration.php
> +                    ->ignoreExtraKeys(false)
Good point, done

2024-04-08 18:21 UTC, DjordyKoert requested changes
This configuration option should more generic to potentially allow more options in the future, this also aligns this new configuration option with the `DumpCommand --html-config` option and also let's it serve as a potential way to customize the default value for `--html-config`.

2024-04-08 18:21 UTC, DjordyKoert commented on src/Render/Html/HtmlOpenApiRenderer.php
> +        $this->htmlConfig = $htmlConfig + ['swagger_ui' => [], 'redocly' => []];
```suggestion
        $this->htmlConfig = $htmlConfig;
```

2024-04-08 18:21 UTC, DjordyKoert commented on src/Render/Html/HtmlOpenApiRenderer.php
> +                    'redocly_config' => $options['redocly_config'] + $this->htmlConfig['redocly'],
```suggestion
                    'redocly_config' => $options['redocly_config'],
```

2024-04-08 18:21 UTC, DjordyKoert commented on src/Render/Html/HtmlOpenApiRenderer.php
> +                'swagger_ui_config' => $options['swagger_ui_config'] + $this->htmlConfig['swagger_ui'],
```suggestion
                'swagger_ui_config' => $options['swagger_ui_config'],
```

2024-04-08 18:21 UTC, DjordyKoert commented on src/Render/Html/HtmlOpenApiRenderer.php
>          $options += [
```suggestion
        $options += $this->htmlConfig + [
```

2024-04-08 18:21 UTC, DjordyKoert commented on src/DependencyInjection/Configuration.php
> +                    ->info('SwaggerUI/Redocly configuration options')
More generic description. Furthermore this section should also include the `assets_mode` config option. https://github.com/nelmio/NelmioApiDocBundle/blob/a585e502725d7e3cfcec25f7a3d59443842006da/src/Render/Html/HtmlOpenApiRenderer.php#L43
```suggestion
                    ->info('UI configuration options')
```

2024-04-08 18:41 UTC, HypeMC commented on src/DependencyInjection/Configuration.php
> +                        ->end()
Done

2024-04-08 18:41 UTC, HypeMC commented on src/Render/Html/HtmlOpenApiRenderer.php
> +        $this->htmlConfig = $htmlConfig + ['swagger_ui' => [], 'redocly' => []];
Done

2024-04-08 18:41 UTC, HypeMC commented on src/Render/Html/HtmlOpenApiRenderer.php
> +                    'redocly_config' => $options['redocly_config'] + $this->htmlConfig['redocly'],
Done

2024-04-08 18:41 UTC, HypeMC commented on src/Render/Html/HtmlOpenApiRenderer.php
> +                'swagger_ui_config' => $options['swagger_ui_config'] + $this->htmlConfig['swagger_ui'],
Done

2024-04-08 18:41 UTC, HypeMC commented on src/Render/Html/HtmlOpenApiRenderer.php
>          $options += [
Done

2024-04-08 18:41 UTC, HypeMC commented on src/DependencyInjection/Configuration.php
> +                    ->info('SwaggerUI/Redocly configuration options')
Done

2024-04-08 18:52 UTC, DjordyKoert requested changes

2024-04-08 19:33 UTC, HypeMC commented on src/Render/Html/HtmlOpenApiRenderer.php
>          ];
Done, I had to add `addDefaultsIfNotSet()` to make sure the keys always exist.

2024-04-08 19:33 UTC, HypeMC commented on tests/DependencyInjection/NelmioApiDocExtensionTest.php
> +    public function testHtmlOpenApiRendererWithHtmlConfig()
Done

2024-04-08 21:25 UTC, DjordyKoert approved these changes

2024-04-18 11:26 UTC, HypeMC commented
I've rebased the PR since there were conflicts.

2024-04-19 08:30 UTC, DjordyKoert commented
> I've rebased the PR since there were conflicts.

Thank you! I was planning on doing it myself but I was not able to find the time for it yet :) I will try and have a look at everything later today if my time allows it

2024-04-19 14:08 UTC, merged

2024-04-19 14:09 UTC, DjordyKoert commented
Thank you @HypeMC :)