PHPStan bump to level 6
nelmio/NelmioApiDocBundle pull request #2259
Opened 2024-04-06 16:24 UTC by DjordyKoert

| Q             | A                                                                                                                         |
|---------------|---------------------------------------------------------------------------------------------------------------------------|
| Bug fix?      | no                                                                                                                    |
| New feature?  | yes                                                                    |
| Deprecations? | no                                                   |
| Issues        | Fix #...  |

Follow-up on https://github.com/nelmio/NelmioApiDocBundle/pull/2249. Bump PHPStan to level 6 with required changes.

2024-04-06 19:54 UTC, DominicLuidold commented
@DjordyKoert If you'd like, you can assign me as a reviewer once this PR is ready to be reviewed :blush:

2024-04-06 22:30 UTC, DjordyKoert commented
> @DjordyKoert If you'd like, you can assign me as a reviewer once this PR is ready to be reviewed 😊

Github does not allow me to assign you as a reviewer so all I can give you is a friendly ping @DominicLuidold :/

It has become quite the PR because pretty much every class (if not all) required a change. I tried my to keep everything without introducing breaking changes so I hope that I didn't miss anything on accident.

2024-04-07 21:00 UTC, DominicLuidold commented
> Github does not allow me to assign you as a reviewer so all I can give you is a friendly ping @DominicLuidold :/

That's fine! I'll have a look at the PR and the changes within the next couple of days.

Thanks already for improving the code quality even further! :smile:

2024-04-13 13:17 UTC, DominicLuidold requested changes
Looking really good - as you said, literally touches the whole project. :sweat_smile: 

I've only found very minor/nit-picky things and one question. Great effort! :tada:

2024-04-13 13:17 UTC, DominicLuidold commented on src/PropertyDescriber/PropertyDescriber.php
>      /** @var PropertyDescriberInterface[] */
```suggestion
    /** @var iterable<PropertyDescriberInterface> */
```

2024-04-13 13:17 UTC, DominicLuidold commented on src/PropertyDescriber/PropertyDescriber.php
> +     * @param PropertyDescriberInterface[] $propertyDescribers
```suggestion
     * @param iterable<PropertyDescriberInterface> $propertyDescribers
```

2024-04-15 16:24 UTC, DjordyKoert commented on src/ModelDescriber/Annotations/PropertyPhpDocReader.php
> +    private DocBlockFactory $docBlockFactory;
No clue why this wasn't caught

2024-04-15 16:36 UTC, DjordyKoert reviewed
found some breaking changes

2024-04-15 16:36 UTC, DjordyKoert commented on src/Render/RenderOpenApi.php
> + */
This should not be marked internal, the service is marked as public https://github.com/nelmio/NelmioApiDocBundle/blob/4b40eecded96ceaa6c74c2ef85c8b6a326f4510c/config/services.xml#L35

```suggestion
```

2024-04-15 16:36 UTC, DjordyKoert commented on src/Render/RenderOpenApi.php
> +    public function renderFromRequest(Request $request, string $format, string $area, array $extraOptions = []): string
class is not final or internal, this would be a breaking change when extending & overwriting the method. https://3v4l.org/oukC0

Parameter type can be added without breaking. https://3v4l.org/o8nDR

```suggestion
    /**
     * @param array<string, mixed> $extraOptions
     *
     * @return string
     */
    public function renderFromRequest(Request $request, string $format, string $area, array $extraOptions = [])
```

2024-04-15 16:38 UTC, DjordyKoert commented on phpstan.dist.neon
> +    checkGenericClassInNonGenericObjectType: false
It wasn't worth the extra effort for me to rewrite things like `ReflectionClass` to `ReflectionClass<object>` 👍

2024-04-15 16:45 UTC, DjordyKoert commented on src/ModelDescriber/Annotations/PropertyPhpDocReader.php
> +    private DocBlockFactory $docBlockFactory;
Ah an update of `phpdocumentor/reflection-docblock` changed this.

`5.3.0`: https://github.com/phpDocumentor/ReflectionDocBlock/blob/622548b623e81ca6d78b721c5e029f4ce664f170/src/DocBlockFactory.php#L58

`5.4.0`: https://github.com/phpDocumentor/ReflectionDocBlock/blob/298d2febfe79d03fe714eb871d5538da55205b1a/src/DocBlockFactory.php#L65

2024-04-15 16:57 UTC, DominicLuidold approved these changes
Looking good - and good catch with the BC breaks! 💯

2024-04-15 17:00 UTC, merged

2024-04-15 17:01 UTC, DjordyKoert commented
> Looking good - and good catch with the BC breaks! 💯

Thank you for helping me with this @DominicLuidold I really appreciate it ❤️