Update CONTRIBUTING guide
nelmio/NelmioApiDocBundle pull request #2261
Opened 2024-04-07 20:56 UTC by DominicLuidold

| Q             | A  |
|---------------|----|
| Bug fix?      | no |
| New feature?  | no |
| Deprecations? | no |
| Issues        | /  |

Rewrites the contributing guide to incorporate recent developments and brings it up to date:
- Updates formatting, renames "rules" to "guidelines", adds mention of [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119), and rephrases test and documentation sections
- Updates the code style section reflecting the changes introduced in #2250 
- Adds code quality section reflecting the changes introduced in #2249

2024-04-08 15:31 UTC, DjordyKoert requested changes
Thank you very much (once again 😄)

A few remarks but everything else looks good 👍

2024-04-08 15:31 UTC, DjordyKoert commented on CONTRIBUTING.md
> +[commit messages that make sense](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
I personally think that this should be a recommendation. I am currently squashing every PR while merging so proper commits aren't necessary for maintaining history. It also helps lower the barrier for others willing to contribute.

It might make it easier to review a PR but I don't see that as reason to require this :)
```suggestion
You SHOULD write [commit messages that make sense](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
```

2024-04-08 15:31 UTC, DjordyKoert commented on CONTRIBUTING.md
>  You SHOULD write documentation.
```suggestion
You SHOULD write (or update) documentation.
```

2024-04-08 20:31 UTC, DominicLuidold commented on CONTRIBUTING.md
> +[commit messages that make sense](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
@DjordyKoert On the note of commit messages: What do you think of [conventional commits](https://www.conventionalcommits.org/) on a PR title level (therefore also for the repository history)? For example, requiring PR titles to follow the mentioned scheme (for this PR it would be `docs: Update CONTRIBUTING guide`).

I think this could provide some benefits in regards to creating changelogs and assessing PRs as well as commits in general at a glance. If you'd be interested, I could open an issue further discussing this topic and also showcasing a GitHub Actions workflow validating PRs and commenting, if necessary, to support potential contributors. 😃

2024-04-08 22:11 UTC, DjordyKoert commented on CONTRIBUTING.md
> +[commit messages that make sense](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
yeah feel free to open an issue about it 👍

2024-04-08 22:11 UTC, DjordyKoert approved these changes

2024-04-11 11:37 UTC, merged

2024-04-11 11:37 UTC, DjordyKoert commented
thank you @DominicLuidold ❤️