chore: Add missing trigger_deprecation calls to deprecated classes, methods
nelmio/NelmioApiDocBundle pull request #2265
Opened 2024-04-13 14:22 UTC by DominicLuidold

| Q             | A   |
|---------------|-----|
| Bug fix?      | no  |
| New feature?  | no  |
| Deprecations? | yes |
| Issues        | /   |

Adds missing deprecation triggers to classes and methods that have been deprecated with a `@deprecated` annotation.

2024-04-13 14:25 UTC, DominicLuidold commented on src/Form/Extension/DocumentationExtension.php
> +
This deprecation is based on the `@deprecated` annotation which will be added to this method as part of #2259.

TODO:
- Update version based on @DjordyKoert's feedback
- Update CHANGELOG.md

2024-04-15 17:26 UTC, DjordyKoert requested changes

2024-04-15 17:26 UTC, DjordyKoert commented on src/Form/Extension/DocumentationExtension.php
> +            '4.26.0',
```suggestion
            '4.25.3',
```

2024-04-15 17:26 UTC, DjordyKoert commented on src/PropertyDescriber/ArrayPropertyDescriber.php
>      public function describe(array $types, OA\Schema $property, ?array $groups = null, ?OA\Schema $schema = null, array $context = [])
We should also deprecate using `null` for the `$schema` parameter

2024-04-20 11:09 UTC, DjordyKoert requested changes

2024-04-20 11:09 UTC, DjordyKoert commented on src/PropertyDescriber/ArrayPropertyDescriber.php
> +        }
Would this way of checking the parameter be better for triggering deprecations?

```suggestion
		if (null !== $groups || func_num_args() >= 3) {
            trigger_deprecation(
                'nelmio/api-doc-bundle',
                '4.17.0',
                'Using the $groups parameter of "%s" is deprecated and will be removed in a future version. Pass groups via $context[\'groups\'].', __METHOD__
            );
        }

        if (\func_num_args() < 4 || null === $schema) {
            trigger_deprecation(
                'nelmio/api-doc-bundle',
                '4.15.0',
                'The "%s()" method will have a new "OA\Schema $schema" arument not defining it is deprecated.', __METHOD__
            );

            $schema = null;
        } else {
            $schema = func_get_arg(3);
        }
```

2024-06-16 10:40 UTC, DominicLuidold commented on src/PropertyDescriber/ArrayPropertyDescriber.php
> +        }
@DjordyKoert I'm not entirely sure that relying on the `func_num_args` count is an approach we should take here. Mainly because we deprecate _not_ defining one argument while also deprecating if the other is defined.

For example, with `func_num_args() >= 3` we wouldn't know if someone calls the method like this, which would be totally valid:
```php
$describer->describe(
    types: $types,
    property: $property,
    schema: $schema,
);
```

While `func_num_args() < 4` would not work if someone calls the method like this, even though `$schema` is not defined/`null`:
```php
    types: $types,
    property: $property,
    groups: $groups,
    context: $context,
```

2024-06-23 18:44 UTC, DominicLuidold commented
@DjordyKoert Is there any way we could merge this PR? I unfortunately always have to keep up with the latest version changes (and update the PHPUnit baseline) after each release to keep the right version number (see e.g. b36a2191ae786eb5454c64622963a421afc20dfd). :sweat_smile:

2024-08-20 09:38 UTC, DominicLuidold commented
> I unfortunately always have to keep up with the latest version changes (and update the PHPUnit baseline) after each release to keep the right version number (see e.g. [b36a219](https://github.com/nelmio/NelmioApiDocBundle/commit/b36a2191ae786eb5454c64622963a421afc20dfd)). 😅

If #2335 is merged before this, that's not necessary anymore (also, some changes would have to be reverted in this PR).

2024-10-17 22:13 UTC, DjordyKoert approved these changes

2024-10-17 22:14 UTC, DjordyKoert commented
Sorry this took way too long than it should have to merge.

Thank you for the time you spend on this @DominicLuidold ❤️

2024-10-17 22:14 UTC, merged