fix(SymfonyConstraintAnnotationReader): disallow null if NotNull attribute is present
nelmio/NelmioApiDocBundle pull request #2329
Opened 2024-08-02 14:52 UTC by jeremyVignelles

| Q             | A                                                                                                                         |
|---------------|---------------------------------------------------------------------------------------------------------------------------|
| Bug fix?      | yes                                                                                                                    |
| New feature?  | no                                                                    |
| Deprecations? | no                                                   |
| Issues        | Fix #2309 |

if a property is set as something like this:

```php
#[OA\Property()]
#[Assert\NotNull(groups: ['validation'])]
private ?string $prop = null;
```

that property will be marked as nullable AND required.
This PR ensures that the nullable property is also set appropriately when a NotNull is set

2024-08-08 14:13 UTC, DjordyKoert approved these changes

2024-08-08 14:49 UTC, DjordyKoert commented
Could you update with master? :)

2024-08-09 19:53 UTC, jeremyVignelles commented
Done, unit tests and code style fixed, commits squashed into one :)
You're good to go :)

2024-08-16 07:50 UTC, DjordyKoert requested changes

2024-08-16 07:50 UTC, DjordyKoert commented on .devcontainer/devcontainer.json
> +// For format details, see https://aka.ms/devcontainer.json. For config options, see the
Could you remove this file?

2024-08-16 12:29 UTC, jeremyVignelles commented on .devcontainer/devcontainer.json
> +// For format details, see https://aka.ms/devcontainer.json. For config options, see the
Sorry, was careful about not pushing it the first time but forgot about it when rebasing.
The file has been removed.

2024-08-16 13:52 UTC, DjordyKoert approved these changes

2024-08-16 13:53 UTC, merged

2024-08-16 13:53 UTC, DjordyKoert commented
Thank you :)