feat(#2056): support configuring serializer per model
nelmio/NelmioApiDocBundle pull request #2342
Opened 2024-09-23 16:18 UTC by herndlm

| Q             | A                                                                                                                         |
|---------------|---------------------------------------------------------------------------------------------------------------------------|
| Bug fix?      | no                                                                                                                    |
| New feature?  | yes                                                                    |
| Deprecations? | no                                                   |
| Issues        | Fix #2056  |

Always registers `JMSModelDescriber` when the bundle is active, independently of the configured global `models.use_jms` option.
If `models.use_jms` is set, then `JMSModelDescriber` will be added with a priority of 50, just as before. If `models.use_jms` is not set, it will be added with -50 so that `ObjectModelDescriber` is used instead. This should not lead to any behavior change.

Adds support to `options.useJms` in the model by early exiting in either `JMSModelDescriber` or `ObjectModelDescriber` when it is either explicitly `false` or `true`. Together with the priorities of the describer this allows to have either JMS or Symfony serializer as default and switch per model if necessary.

2024-09-23 16:20 UTC, herndlm commented
phpstan and unit tests were already not working locally for me and I didn't do much debugging yet :/

2024-09-23 18:58 UTC, herndlm commented on src/Model/Model.php
> +        return md5(serialize([$this->type, $this->serializationContext, $this->options]));
ah dang, I noticed that this is actually breaking something in my use case. My model includes an property with a list ob objects and a PHPDoc type-hint of for them. https://github.com/nelmio/NelmioApiDocBundle/blob/277fa17b912be31b5170e49f0924b1028058c938/src/PropertyDescriber/ObjectPropertyDescriber.php#L47 is creating the model, but because no options from the original model are passed it leads to a different hash and then incorrect usage of the JMS serializer :/

2024-09-23 19:02 UTC, herndlm commented on src/Model/Model.php
> +        return md5(serialize([$this->type, $this->serializationContext, $this->options]));
Changing that interface to pass through the options is not OK I suppose, using context to add `useJms` would be fine though, since it is passed through already, but feels like a hack

2024-09-24 09:20 UTC, DjordyKoert requested changes

2024-09-24 09:20 UTC, DjordyKoert commented on src/Model/Model.php
> +        return md5(serialize([$this->type, $this->serializationContext, $this->options]));
`options` is only used for [`symfony/form`](https://symfony.com/doc/current/forms.html#passing-options-to-forms). 

I would rather add `useJms` into `serializationContext`. This would also prevent us from having to add another parameter `options` to every describer (and `PropertyDescriberInterface`). Are you able to change this? 😃 

> the model could also become a new useJms argument / property itself

I would rather not add a new property specific for this use-case to the `Model` class, it would start cluttering the constructor quite a bit if we were to do this everytime 😄

2024-09-24 09:27 UTC, herndlm commented on src/Model/Model.php
> +        return md5(serialize([$this->type, $this->serializationContext, $this->options]));
of course, that makes sense. sure, I'll adapt it right away 😊

2024-09-24 09:57 UTC, herndlm commented on src/Model/Model.php
> +        return md5(serialize([$this->type, $this->serializationContext, $this->options]));
done. only one thing I'm not super happy about - the changes (setting useJms: false) in `SymfonyMapRequestPayloadDescriber` lead to model schema duplication in a existing test for `Controller2209` because the same model is used before already. In that case, since JMS is off, changing the serializationContext does not add any benefits. Not sure if we're just fine with this or I should e.g. inject the global `useJms` and only explicitly set it to false IF JMS is really active.

WDYT?

2024-09-24 11:57 UTC, DjordyKoert commented on src/Model/Model.php
> +        return md5(serialize([$this->type, $this->serializationContext, $this->options]));
There shouldn't be any need to set `useJms` there. 

If users want to set that value they can explicely set it on the `#[MapRequestPayload]` attribute: 
```php

#[MapRequestPayload(serializationContext: ['useJms' => true])]
```

2024-09-24 11:57 UTC, DjordyKoert requested changes

2024-09-24 11:57 UTC, DjordyKoert commented on src/RouteDescriber/RouteArgumentDescriber/SymfonyMapQueryStringDescriber.php
> +            ['useJms' => false] + $attribute->serializationContext
```suggestion
            $attribute->serializationContext
```

2024-09-24 11:57 UTC, DjordyKoert commented on src/RouteDescriber/RouteArgumentDescriber/SymfonyMapRequestPayloadDescriber.php
> +            ['useJms' => false] + $attribute->serializationContext
```suggestion
            $attribute->serializationContext
```

2024-09-24 12:03 UTC, herndlm commented on src/Model/Model.php
> +        return md5(serialize([$this->type, $this->serializationContext, $this->options]));
what I slightly dislike there is that e.g. `MapRequestPayload` is always deserialized using Symfony serializer (via https://github.com/symfony/symfony/blob/3c7124ea938b741f5bfffd97364320eac8232d63/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php).

But if I have JMS installed, it would try to use JMS for Swagger docs instead, which is always wrong IMO. And my thought was that setting `'useJms' => false` would make it properly describe the DTO out of the box even if JMS is installed.

2024-09-24 12:05 UTC, DjordyKoert requested changes

2024-09-24 12:05 UTC, DjordyKoert commented on src/ModelDescriber/ObjectModelDescriber.php
> +
This check now always requires `useJms` to be defined, which will cause this describer to never be run UNLESS it's defined as `['useJms' => true]` on every model.

This check can be removed by relying on the order (priority) of the called describers.

 ```suggestion
```

2024-09-24 12:07 UTC, herndlm commented on src/Model/Model.php
> +        return md5(serialize([$this->type, $this->serializationContext, $this->options]));
it's really just relevant if JMS is used by default. I think we'll turn of JMS by default and only enable it for specific old endpoints and then this would not affect me. but it still bothers me slightly 😅

2024-09-24 12:10 UTC, DjordyKoert commented on src/Model/Model.php
> +        return md5(serialize([$this->type, $this->serializationContext, $this->options]));
I agree that it sounds weird but I would still prefer the user of this bundle to explicitly define how they want it to behave.

The current master version is currently also using the `JMSSerializer` whenever the jms is available for describing models from `#[MapRequestPayload]`.

2024-09-24 12:16 UTC, herndlm commented on src/ModelDescriber/ObjectModelDescriber.php
> +
sorry, I don't fully get what you mean, the order of those has been dealt with, this code only makes sure that if Symfony is the default (higher order) one but `useJms` is true that it actually uses JMS instead.

2024-09-24 12:27 UTC, herndlm commented on src/ModelDescriber/ObjectModelDescriber.php
> +
ah wait, I think I got it. you mean the `JMSModelDescriber` should _always_ run first and that way we don't need this, right?

2024-09-24 12:31 UTC, herndlm commented on src/ModelDescriber/ObjectModelDescriber.php
> +
wait no, that doesn't work. I'd like to be able to have Symfony by default (`nelmio_api_doc.models.use_jms: false`) but still use JMS for some endpoints BUT preferably not have configure `'useJms' => false` in all new endpoints, but only  `'useJms' => true` in the old ones. If that makes sense?

2024-09-24 12:38 UTC, DjordyKoert commented on src/ModelDescriber/ObjectModelDescriber.php
> +
> ah wait, I think I got it. you mean the JMSModelDescriber should always run first and that way we don't need this, right? I made it more dynamical but that leads to this conditional being needed.

Correct, the priority of 50 is going to ensure the `JMSModelDescriber` is ran before the others.

2024-09-24 12:46 UTC, herndlm commented on src/ModelDescriber/ObjectModelDescriber.php
> +
I agree, it feels a bit dirty. What about this
- we use the global `use_jms` to configure listener priority to have no behavior changes
  - if it's not configured explicitly, it will be set to true if the bundle is there
  - if it's set to true the JMS describer will run first
  - if it's set to false the ObjectModel describer will run fist
- instead of adding `useJms` I could add a `disableJms` and `disableSymfony` config. not sure about the names, but it should suggest that it only leads to disabling one of them
- JMS describer exits early if `disableJms` is configured
- ObjectModel describer exits early if `disableSymfony` (or however we call it) is configured

that way less magic is involved and people can still have either one by default and prefer the other one for specific endpoints by disabling the default one

2024-09-24 12:49 UTC, DjordyKoert commented on src/ModelDescriber/ObjectModelDescriber.php
> +
> but still use JMS for some endpoints BUT preferably not have configure 'useJms' => false in all new endpoints, but only 'useJms' => true in the old ones. If that makes sense?

From your issue I read:
> I'd basically would need to be able to disable nelmio_api_doc.models.use_jms for new endpoints only.

This is of course a personal preference but IMO using a way to opt-out on your new endpoints is better than deciding to opt-in on your old endpoints. That way there is:
1. No need to change your config (`nelmio_api_doc.models.use_jms`)
2. You can globally disable `useJms` and you won't necessarily have to edit your `#[MapRequestPayload]`'s after all your old endpoint are gone.

2024-09-24 12:55 UTC, herndlm commented on src/ModelDescriber/ObjectModelDescriber.php
> +
would you accept the opt out of both JMS or Symfony I suggested in the previous comment? that could be a good and simple solution to deal with cases in both direction.

2024-09-24 13:02 UTC, herndlm commented on src/ModelDescriber/ObjectModelDescriber.php
> +
ok that's reasonable. I hoped I could somehow opt-in to JMS 😊 but we can deal with this. I'll adapt the PR so that it only allows us to opt-out of JMS.

2024-09-24 13:08 UTC, DjordyKoert commented on src/ModelDescriber/ObjectModelDescriber.php
> +
> I hoped I could somehow opt-in to JMS

You could of course decorate the `ObjectModelDescriber` and add this logic yourself on your project(s) if this is something you want / need. 😄 
https://symfony.com/doc/current/service_container/service_decoration.html

2024-09-24 13:15 UTC, herndlm commented on src/ModelDescriber/ObjectModelDescriber.php
> +
ok done, we successfully discussed away most of the original code 😂

2024-09-24 13:17 UTC, herndlm commented
just for the record if somebody is looking for this: if opting out of Symfony serializer is needed for special reasons - it could be achieved with a patch as simple as the following:

```patch
diff --git a/src/ModelDescriber/ObjectModelDescriber.php b/src/ModelDescriber/ObjectModelDescriber.php
index f119bde..d1ed4f3 100644
--- a/src/ModelDescriber/ObjectModelDescriber.php
+++ b/src/ModelDescriber/ObjectModelDescriber.php
@@ -235,6 +235,10 @@ class ObjectModelDescriber implements ModelDescriberInterface, ModelRegistryAwar

     public function supports(Model $model): bool
     {
+        if (($model->getSerializationContext()['useSymfony'] ?? null) === false) {
+            return false;
+        }
+
         return Type::BUILTIN_TYPE_OBJECT === $model->getType()->getBuiltinType()
             && (class_exists($model->getType()->getClassName()) || interface_exists($model->getType()->getClassName()));
     }
```

2024-09-24 13:56 UTC, DjordyKoert approved these changes

2024-09-24 13:56 UTC, merged

2024-09-24 13:56 UTC, DjordyKoert commented
Thank you very much for your contributions @herndlm 😄

2024-09-24 20:01 UTC, kevinpapst commented
I am describing my models in YAML:
```yaml
nelmio_api_doc:
    models:
        use_jms: true
        names:
            - { alias: FooBar, type: App\Entity\FooBar, groups: [Default, Entity] }
```
and annotation
```
    #[OA\Response(response: 200, description: '...', content: new OA\JsonContent(type: 'array', items: new OA\Items(ref: '#/components/schemas/FooBar')))]
```
Any chance I can use that new feature? 
If not, any hint how/where to start implementing support?

2024-09-26 15:50 UTC, herndlm commented
> I am describing my models in YAML:
> 
> ```yaml
> nelmio_api_doc:
>     models:
>         use_jms: true
>         names:
>             - { alias: FooBar, type: App\Entity\FooBar, groups: [Default, Entity] }
> ```
> 
> and annotation
> 
> ```
>     #[OA\Response(response: 200, description: '...', content: new OA\JsonContent(type: 'array', items: new OA\Items(ref: '#/components/schemas/FooBar')))]
> ```
> 
> Any chance I can use that new feature? If not, any hint how/where to start implementing support?

seems to be not possible right now, but it look like just 2 places have to be adapted.

- https://github.com/nelmio/NelmioApiDocBundle/blob/322c47b9fa3c5913ec9bbeba537a32407151be73/src/DependencyInjection/NelmioApiDocExtension.php#L304-L305
- https://github.com/nelmio/NelmioApiDocBundle/blob/322c47b9fa3c5913ec9bbeba537a32407151be73/src/Model/ModelRegistry.php#L70

I think being able to specify the serializationContext there too makes sense and I can open a PR for it as well. In the end @DjordyKoert has to decide I suppose :)

2024-09-26 16:17 UTC, kevinpapst commented
Feature parity would be great ❤️

2024-09-27 10:08 UTC, herndlm commented
fyi this might close also https://github.com/nelmio/NelmioApiDocBundle/issues/1886