feat: support configuring all params in alternative name models
nelmio/NelmioApiDocBundle pull request #2345
Opened 2024-09-27 09:50 UTC by herndlm

| Q             | A                                                                                                                         |
|---------------|---------------------------------------------------------------------------------------------------------------------------|
| Bug fix?      | no                                                                                                                    |
| New feature?  | yes                                                                    |
| Deprecations? | no                                                   |
| Issues        | Fix #...  |

Adds feature parity to model creation in yaml via `nelmio_api_doc.models.names` by also supporting `options` and `serializationContext`.

Tested in a local project, e.g.
```yaml
    models:
        names:
            - { alias: Error, type: App\Model\Error, options:  { foo: bar }, serializationContext: { useJms: false }  }
```

lead to
![grafik](https://github.com/user-attachments/assets/7556c399-9219-45cb-9d68-b50be87fed67)

inspired by https://github.com/nelmio/NelmioApiDocBundle/pull/2342#issuecomment-2372260584
fyi @kevinpapst

it's the first time I touch this Symfony Config TreeBuilder stuff btw..

2024-09-27 10:04 UTC, herndlm commented
fyi @DjordyKoert

2024-09-27 11:22 UTC, kevinpapst commented on src/DependencyInjection/Configuration.php
> +                                    ->arrayNode('serializationContext')
Might be good to validate the possible keys? Otherwise people can put in arbitrary data here.
Better be strict about it, because if you e.g. use a wrong name, you then get a clear hint from the Symfony exception which keys are available.

2024-09-27 13:36 UTC, DjordyKoert commented on src/DependencyInjection/Configuration.php
> +                                    ->arrayNode('serializationContext')
It should be possible to use any value here. This might even be used for users who do some logic based inside their custom-made describers.

2024-09-27 13:41 UTC, kevinpapst commented on src/DependencyInjection/Configuration.php
> +                                    ->arrayNode('serializationContext')
Ah, in that case, prototype is fine. Thanks for the clarification 👍

2024-09-27 13:42 UTC, DjordyKoert requested changes

2024-09-27 13:42 UTC, DjordyKoert commented on CHANGELOG.md
> +* Added support to configure `options` and `serializationContext` via `nelmio_api_doc.models.names` as well.
```suggestion
* Added support to configure `options` and `serializationContext` via `nelmio_api_doc.models.names`.
```

2024-09-27 13:42 UTC, DjordyKoert commented on src/DependencyInjection/Configuration.php
> +                                            ->ifTrue(function ($v) { return null !== $v && !is_array($v); })
Missing test for this

2024-09-27 13:42 UTC, DjordyKoert commented on tests/DependencyInjection/ConfigurationTest.php
> +                        'serializationContext' => ['useJms' => false],
Lets also test that anything can be used here

```suggestion
                        'serializationContext' => ['useJms' => false, 'foo' => 'bar'],
```

2024-09-27 13:42 UTC, DjordyKoert commented on tests/Model/ModelRegistryTest.php
> +                'serializationContext' => [],
Old tests shouldn't be needed to be changed right?

2024-09-27 14:09 UTC, herndlm commented on tests/Model/ModelRegistryTest.php
> +                'serializationContext' => [],
that's because in ModelRegistry it is assumed that those new keys in `$alternativeNames` are set, which they always should be, because they have a default AFAIK.
But, we can keep BC here by not assuming that, sure :) adapted

2024-09-27 14:12 UTC, herndlm commented on src/DependencyInjection/Configuration.php
> +                                            ->ifTrue(function ($v) { return null !== $v && !is_array($v); })
added :)

2024-09-30 13:01 UTC, DjordyKoert approved these changes

2024-09-30 13:01 UTC, merged

2024-09-30 13:01 UTC, DjordyKoert commented
@herndlm sorry had a busy weekend 😅 

Anyways thank you for the PR's! ❤️

2024-09-30 13:03 UTC, herndlm commented
Thanks! I wasn't expecting you to check something here on the weekend, no worries :)